# coding: utf-8
import torch
from torch.utils.data import Dataset
import numpy as np
import cv2
import os
import random
from pathlib import Path

import albumentations as A


# ---------------------------------------------------------------------------
# PreprocessedDataset: loads pre-saved .pt files (no runtime processing)
# ---------------------------------------------------------------------------

class PreprocessedDataset(Dataset):
    """Loads pre-processed .pt files generated by preprocess_to_pt.py."""

    def __init__(self, preprocessed_dir):
        self.preprocessed_dir = Path(preprocessed_dir)
        self.file_list = sorted(list(self.preprocessed_dir.glob('*.pt')))

        if len(self.file_list) == 0:
            raise RuntimeError(
                f"No preprocessed data found. Run: python preprocess_to_pt.py\n"
                f"Search path: {self.preprocessed_dir}"
            )
        print(f"PreprocessedDataset: {len(self.file_list)} samples from {self.preprocessed_dir}")

    def __len__(self):
        return len(self.file_list)

    def __getitem__(self, idx):
        data = torch.load(self.file_list[idx])
        return {'image': data['image'], 'mask': data['mask']}


# ---------------------------------------------------------------------------
# CatheterPreprocessingDataset: mixed-size strategy + geometric augmentation
# ---------------------------------------------------------------------------

class CatheterPreprocessingDataset(Dataset):
    """
    Dataset for catheter/guidewire segmentation.

    Preprocessing (no resize ever):
      - Small image (longest edge <= target_size): pad with black border
      - Large image (longest edge  > target_size): random crop (train)
                                                center crop (val/test)

    Augmentation (train mode only):
      HorizontalFlip, VerticalFlip, ShiftScaleRotate
    """

    def __init__(self, image_paths, mask_paths, target_size=512,
                 use_clahe=False, mean=None, std=None, mode='train',
                 fg_crop=False, fg_crop_sizes=(256, 320, 384),
                 intensity_aug=False):
        if len(image_paths) != len(mask_paths):
            raise ValueError("Number of images and masks must be equal.")

        self.image_paths = image_paths
        self.mask_paths  = mask_paths
        self.target_size = target_size
        self.use_clahe   = use_clahe
        self.mode        = mode
        self.fg_crop     = fg_crop
        self.fg_crop_sizes = tuple(fg_crop_sizes) if fg_crop_sizes else (256, 320, 384)
        self.intensity_aug = bool(intensity_aug)

        # normalize stats (HWC broadcast)
        self.mean: np.ndarray = np.array(mean if mean is not None else [0.485, 0.456, 0.406],
                                         dtype=np.float32)[np.newaxis, np.newaxis, :]
        self.std: np.ndarray = np.array(std if std is not None else [0.229, 0.224, 0.225],
                                        dtype=np.float32)[np.newaxis, np.newaxis, :]

        print(f"Dataset: {len(image_paths)} samples | mode={mode} | "
              f"target={target_size} | clahe={use_clahe} | fg_crop={self.fg_crop} | intensity_aug={self.intensity_aug}")

        # Augmentation pipeline (train only)
        if self.mode == 'train':
            aug_list = [
                A.HorizontalFlip(p=0.5),
                A.VerticalFlip(p=0.2),
                A.ShiftScaleRotate(
                    shift_limit=0.05,
                    scale_limit=0.05,
                    rotate_limit=15,
                    border_mode=cv2.BORDER_CONSTANT,
                    value=0,
                    mask_value=0,
                    p=0.7,
                ),
            ]

            # Intensity augmentations (brightness/contrast/gamma/noise/blur) are applied with moderate probability to improve robustness.
            # Note: these are applied after cropping, so they do not affect the foreground cropping process.
            if self.intensity_aug:
                aug_list.extend([
                    A.RandomBrightnessContrast(
                        brightness_limit=0.15,
                        contrast_limit=0.15,
                        p=0.5,
                    ),
                    A.RandomGamma(
                        gamma_limit=(85, 115),
                        p=0.3,
                    ),
                    A.GaussNoise(
                        var_limit=(5.0, 25.0),
                        mean=0,
                        per_channel=True,
                        p=0.3,
                    ),
                    A.OneOf([
                        A.GaussianBlur(blur_limit=(3, 5), p=1.0),
                        A.MotionBlur(blur_limit=5, p=1.0),
                    ], p=0.15),
                ])

            self.augment = A.Compose(aug_list)  # type: ignore[arg-type]
        else:
            self.augment = None

    def __len__(self):
        return len(self.image_paths)

    # ------------------------------------------------------------------
    def _pad_to_target(self, image, mask):
        """Pad image/mask so both dims >= target_size (no upscaling)."""
        h, w   = image.shape[:2]
        pad_h  = max(0, self.target_size - h)
        pad_w  = max(0, self.target_size - w)
        top    = pad_h // 2;  bottom = pad_h - top
        left   = pad_w // 2;  right  = pad_w - left
        image = cv2.copyMakeBorder(image, top, bottom, left, right,
                                   cv2.BORDER_CONSTANT, value=(0, 0, 0))
        mask  = cv2.copyMakeBorder(mask,  top, bottom, left, right,
                                   cv2.BORDER_CONSTANT, value=0)
        return image, mask

    def _crop_to_target(self, image, mask):
        """Crop target_size x target_size patch. Pad first if any dim < target_size.

        Train mode — foreground-centered crop:
          1. Find all foreground pixels (class > 0) in the mask.
          2. Randomly pick one as anchor; add random jitter so the anchor
             is not always at the exact crop centre (keeps diversity).
          3. Clamp the crop window to stay inside the image.
          Falls back to pure random crop when the image has no foreground.

        Val/test mode — centre crop (deterministic).
        """
        h, w = image.shape[:2]
        if h < self.target_size or w < self.target_size:
            image, mask = self._pad_to_target(image, mask)
            h, w = image.shape[:2]

        if self.mode == 'train':
            # ── foreground-centered crop ──────────────────────────────────
            fg_ys, fg_xs = np.where(mask > 0)

            if len(fg_ys) > 0:
                # Pick a random foreground pixel as anchor
                pick    = random.randint(0, len(fg_ys) - 1)
                cy, cx  = int(fg_ys[pick]), int(fg_xs[pick])

                # Jitter: shift anchor up to half the crop size away from centre
                half    = self.target_size // 2
                jitter  = self.target_size // 4          # ±25% of crop size
                cy += random.randint(-jitter, jitter)
                cx += random.randint(-jitter, jitter)

                # Compute top-left corner, then clamp inside image
                y0 = max(0, min(cy - half, h - self.target_size))
                x0 = max(0, min(cx - half, w - self.target_size))
            else:
                # No foreground: fall back to pure random crop
                y0 = random.randint(0, h - self.target_size)
                x0 = random.randint(0, w - self.target_size)
        else:
            y0 = (h - self.target_size) // 2
            x0 = (w - self.target_size) // 2

        return (image[y0:y0 + self.target_size, x0:x0 + self.target_size],
                mask [y0:y0 + self.target_size, x0:x0 + self.target_size])

    # ------------------------------------------------------------------
    def _fg_crop_and_resize(self, image, mask):
        """Foreground-aware multi-scale crop followed by resize to target_size.
        1) Compute the foreground (>0) bounding box; fall back to center crop if no foreground exists.
        2) Randomly choose a crop scale (for example 256/320/384) and sample a window near the foreground center with jitter.
        3) Clip to image bounds; pad first if needed; crop and then resize to target_size.
        """
        h, w = image.shape[:2]
        crop_size = random.choice(self.fg_crop_sizes)

        # If the image is smaller than the crop size, pad first so it is at least crop_size.
        if h < crop_size or w < crop_size:
            pad_h = max(0, crop_size - h)
            pad_w = max(0, crop_size - w)
            top = pad_h // 2; bottom = pad_h - top
            left = pad_w // 2; right = pad_w - left
            image = cv2.copyMakeBorder(image, top, bottom, left, right,
                                       cv2.BORDER_CONSTANT, value=(0, 0, 0))
            mask  = cv2.copyMakeBorder(mask,  top, bottom, left, right,
                                       cv2.BORDER_CONSTANT, value=0)
            h, w = image.shape[:2]

        # Foreground bounding box.
        ys, xs = np.where(mask > 0)
        if len(ys) == 0:
            # No foreground: fall back to center crop.
            y0 = max(0, (h - crop_size) // 2)
            x0 = max(0, (w - crop_size) // 2)
        else:
            y_min, y_max = ys.min(), ys.max()
            x_min, x_max = xs.min(), xs.max()
            cy = (y_min + y_max) // 2
            cx = (x_min + x_max) // 2
            jitter = crop_size // 4  # ±25% jitter.
            cy += random.randint(-jitter, jitter)
            cx += random.randint(-jitter, jitter)
            half = crop_size // 2
            y0 = max(0, min(cy - half, h - crop_size))
            x0 = max(0, min(cx - half, w - crop_size))

        y1 = y0 + crop_size
        x1 = x0 + crop_size
        crop_img = image[y0:y1, x0:x1]
        crop_msk = mask[y0:y1, x0:x1]

        # Resize the cropped patch to target_size.
        resized_img = cv2.resize(crop_img, (self.target_size, self.target_size), interpolation=cv2.INTER_LINEAR)
        resized_msk = cv2.resize(crop_msk, (self.target_size, self.target_size), interpolation=cv2.INTER_NEAREST)
        return resized_img, resized_msk

    # ------------------------------------------------------------------
    def __getitem__(self, idx):
        # 1. Load image
        image = cv2.imread(self.image_paths[idx], cv2.IMREAD_COLOR)

        # 2. Load mask (.npy)
        try:
            mask = np.load(self.mask_paths[idx])
        except Exception as e:
            print(f"Error loading mask {self.mask_paths[idx]}: {e}")
            mask = None

        if image is None or mask is None:
            return self.__getitem__(random.randint(0, len(self) - 1))

        # 3. Use the mixed-size strategy (no resize) or foreground crop + resize.
        if self.fg_crop and self.mode == 'train':
            image, mask = self._fg_crop_and_resize(image, mask)
        else:
            if max(image.shape[:2]) <= self.target_size:
                image, mask = self._pad_to_target(image, mask)
            else:
                image, mask = self._crop_to_target(image, mask)

        # 4. Geometric augmentation (train only, image and mask in sync)
        if self.augment is not None:
            aug   = self.augment(image=image, mask=mask.astype(np.int32))
            image = aug['image']
            mask  = aug['mask']

        # 5. CLAHE contrast enhancement (optional)
        if self.use_clahe:
            gray  = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
            clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
            image = cv2.cvtColor(clahe.apply(gray), cv2.COLOR_GRAY2BGR)

        # 6. Normalize and convert to tensor (HWC -> CHW)
        image = (image.astype(np.float32) / 255.0 - self.mean) / self.std
        return {
            'image': torch.from_numpy(image).permute(2, 0, 1),
            'mask':  torch.from_numpy(mask.astype(np.float32)).long(),
        }


# ---------------------------------------------------------------------------
# Quick smoke-test
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    from torch.utils.data import DataLoader

    IMAGE_ROOT = "segmentation/animal_train/images"
    MASK_ROOT  = "segmentation/animal_train/masks"

    image_paths, mask_paths = [], []
    for filename in sorted(os.listdir(IMAGE_ROOT)):
        if filename.endswith(('.png', '.jpg', '.jpeg')):
            img_p  = os.path.join(IMAGE_ROOT, filename)
            mask_p = os.path.join(MASK_ROOT, os.path.splitext(filename)[0] + '.npy')
            if os.path.exists(img_p) and os.path.exists(mask_p):
                image_paths.append(img_p)
                mask_paths.append(mask_p)

    if not image_paths:
        print("No valid pairs found.")
    else:
        ds     = CatheterPreprocessingDataset(image_paths, mask_paths, target_size=512)
        loader = DataLoader(ds, batch_size=2, num_workers=0)
        batch  = next(iter(loader))
        print(f"image: {batch['image'].shape}  mask: {batch['mask'].shape}")
    print("Done.")
